### ISSUE TITLE
Downloading some videos does not work

### ISSUE THREAD

**Issue by sodevrom** [Galibri/apbd-yt-downloader#1]
Hello
 I wanted to use your script, but unfortunately it does not work with all videos. 
 For example, one of the video it fails to download:
https://www.youtube.com/watch?v=7x37bE_ZZY4

 Can you fix it?
  Thanks

**Comment by Galibri** [comment]
@sodevrom Thanks for your feedback! I should rewrite the script to make it work for all the videos. Will update soon.

**Comment by sodevrom** [comment]
Please let me know if you can manage to fix it. Thanks a lot!!

**Comment by Galibri** [comment]
Youtube changed some api rules, so I have to fully replace my code with a new one. I am gonna archive this repository and going to make a new one. Thanks
